import { DOTS, FLOWER_SUIT, WIND_SUIT } from "../constants";
import type { MahjongCard } from "../types";

export const CARD_2026: MahjongCard = {
  name: "2026",
  hands: [
    // #region 2026
    {
      section: "2026",
      melds: [
        { numbers: ["222"], suit: "G" },
        { numbers: ["000"], suit: DOTS },
        { numbers: ["2222"], suit: "R" },
        { numbers: ["6666"], suit: "R" },
      ],
      text: "Any 2 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "2026",
      melds: [
        { numbers: ["2026"], suit: "G" },
        { numbers: ["DDD"], suit: "G" },
        { numbers: ["2222", "6666"], suit: "R" },
        { numbers: ["DDD"], suit: "R" },
      ],
      text: "Any 2 Suits w Matching Dragons, Kong 2 or 6",
      value: 25,
      concealed: false,
    },
    {
      section: "2026",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["2026"], suit: "G" },
        { numbers: ["222"], suit: "R" },
        { numbers: ["6666"], suit: "B" },
      ],
      text: "Any 3 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "2026",
      melds: [
        { numbers: ["22"], suit: "G" },
        { numbers: ["00"], suit: DOTS },
        { numbers: ["222"], suit: "R" },
        { numbers: ["666"], suit: "B" },
        { numbers: ["NEWS"], suit: WIND_SUIT },
      ],
      text: "Any 2 Suits",
      value: 30,
      concealed: false,
    },
    // #endregion

    // #region 2468
    {
      section: "2468",
      melds: [
        { numbers: ["222"], suit: "B" },
        { numbers: ["444"], suit: "B" },
        { numbers: ["6666"], suit: "B" },
        { numbers: ["8888"], suit: "B" },
      ],
      text: "Any 1 or 2 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "2468",
      melds: [
        { numbers: ["222"], suit: "G" },
        { numbers: ["444"], suit: "G" },
        { numbers: ["6666"], suit: "R" },
        { numbers: ["8888"], suit: "R" },
      ],
      text: "Any 1 or 2 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "2468",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["2222"], suit: "G" },
        { numbers: ["44"], suit: "R" },
        { numbers: ["66"], suit: "R" },
        { numbers: ["8888"], suit: "G" },
      ],
      text: "Any 2 Suits",
      value: 30,
      concealed: false,
    },
    {
      section: "2468",
      melds: [
        { numbers: ["EE"], suit: WIND_SUIT },
        { numbers: ["22"], suit: "B" },
        { numbers: ["444"], suit: "B" },
        { numbers: ["666"], suit: "B" },
        { numbers: ["88"], suit: "B" },
        { numbers: ["WW"], suit: WIND_SUIT },
      ],
      text: "Any 1 Suit, East and West Only",
      value: 30,
      concealed: false,
    },
    {
      section: "2468",
      melds: [
        { numbers: ["2222"], suit: "G" },
        { numbers: ["DDD"], suit: "G" },
        { numbers: ["8888"], suit: "R" },
        { numbers: ["DDD"], suit: "R" },
      ],
      text: "Any 2 Suits w Matching Dragons, These Nos. Only",
      value: 25,
      concealed: false,
    },
    {
      section: "2468",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["22"], suit: "B" },
        { numbers: ["44"], suit: "B" },
        { numbers: ["666"], suit: "B" },
        { numbers: ["8888"], suit: "B" },
      ],
      text: "Any 1 Suit",
      value: 25,
      concealed: false,
    },
    {
      section: "2468",
      melds: [
        { numbers: ["2468"], suit: "G" },
        { numbers: ["2222", "4444", "6666", "8888"], suit: "R" },
        { numbers: ["D"], suit: "R" },
        { numbers: ["2222", "4444", "6666", "8888"], suit: "B" },
        { numbers: ["D"], suit: "B" },
      ],
      text: "Any 3 Suits, Like Kongs 2,4,6 or 8 w Matching Dragon",
      value: 25,
      concealed: false,
    },
    {
      section: "2468",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["2468"], suit: "G" },
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["2222", "4444", "6666", "8888"], suit: "R" },
      ],
      text: "Any 2 Suits, Kong 2,4,6 or 8",
      value: 30,
      concealed: false,
    },
    {
      section: "2468",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["246"], suit: "G" },
        { numbers: ["888"], suit: "G" },
        { numbers: ["246"], suit: "R" },
        { numbers: ["888"], suit: "R" },
      ],
      text: "Any 2 Suits",
      value: 30,
      concealed: true,
    },
    // #endregion

    // #region ANY LIKE NUMBERS
    {
      section: "Any Like Numbers",
      melds: [
        { numbers: ["1111", "2222", "3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "G" },
        { numbers: ["FFFFFF"], suit: FLOWER_SUIT },
        { numbers: ["1111", "2222", "3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "R" },
      ],
      text: "Any 2 Suits",
      value: 30,
      concealed: false,
    },
    {
      section: "Any Like Numbers",
      melds: [
        { numbers: ["1111", "2222", "3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "G" },
        { numbers: ["D"], suit: "G" },
        { numbers: ["111", "222", "333", "444", "555", "666", "777", "888", "999"], suit: "R" },
        { numbers: ["D"], suit: "R" },
        { numbers: ["1111", "2222", "3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "B" },
        { numbers: ["D"], suit: "B" },
      ],
      text: "Any 3 Suits w Matching Dragon",
      value: 25,
      concealed: false,
    },
    {
      section: "Any Like Numbers",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["1111", "2222", "3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "G" },
        { numbers: ["11", "22", "33", "44", "55", "66", "77", "88", "99"], suit: "R" },
        { numbers: ["1111", "2222", "3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "B" },
        { numbers: ["DD"], suit: "G" },
      ],
      text: "Any 3 Suits w Any Dragon",
      value: 25,
      concealed: false,
    },
    // #endregion

    // #region QUINTS
    {
      section: "Quints",
      melds: [
        { numbers: ["11111", "22222", "33333", "44444", "55555", "66666", "77777", "88888", "99999"], suit: "G" },
        { numbers: ["1111", "2222", "3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "R" },
        { numbers: ["11111", "22222", "33333", "44444", "55555", "66666", "77777", "88888", "99999"], suit: "B" },
      ],
      text: "Any 3 Suits, Any Like Nos.",
      value: 40,
      concealed: false,
    },
    {
      section: "Quints",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["11111", "22222", "33333", "44444", "55555", "66666", "77777"], suit: "G" },
        { numbers: ["22", "33", "44", "55", "66", "77", "88"], suit: "G" },
        { numbers: ["33333", "44444", "55555", "66666", "77777", "88888", "99999"], suit: "G" },
      ],
      text: "Any 1 Suit, Any 3 Consec. Nos.",
      value: 45,
      concealed: false,
    },
    {
      section: "Quints",
      melds: [
        { numbers: Array.from({ length: 9 }, (_, i) => (i + 1).toString().repeat(4)), suit: "G" },
        { numbers: Array.from({ length: 9 }, () => Array.from({ length: 9 }, (_, i) => (i + 1).toString().repeat(4))).flatMap(i => i), suit: "G" },
        { numbers: ["DDDD"], suit: "R" },
      ],
      text: "Any 2 Nos. in Any 1 Suit w Opp. Dragon",
      value: 40,
      concealed: false,
    },
    // #endregion

    // #region CONSECUTIVE RUN
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["11"], suit: "B" },
        { numbers: ["222"], suit: "B" },
        { numbers: ["33"], suit: "B" },
        { numbers: ["444"], suit: "B" },
        { numbers: ["5555"], suit: "B" },
      ],
      text: "Any 1 Suit, These Nos. Only",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["55"], suit: "B" },
        { numbers: ["666"], suit: "B" },
        { numbers: ["77"], suit: "B" },
        { numbers: ["888"], suit: "B" },
        { numbers: ["9999"], suit: "B" },
      ],
      text: "Any 1 Suit, These Nos. Only",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["1111", "2222", "3333", "4444", "5555"], suit: "B" },
        { numbers: ["234", "345", "456", "567", "678"], suit: "B" },
        { numbers: ["5555", "6666", "7777", "8888", "9999"], suit: "B" },
      ],
      text: "Any 1 or 2 Suits, Any 5 Consec. Nos.",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["1111", "2222", "3333", "4444", "5555"], suit: "G" },
        { numbers: ["234", "345", "456", "567", "678"], suit: "R" },
        { numbers: ["5555", "6666", "7777", "8888", "9999"], suit: "G" },
      ],
      text: "Any 1 or 2 Suits, Any 5 Consec. Nos.",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["11", "22", "33", "44", "55", "66", "77"], suit: "G" },
        { numbers: ["22", "33", "44", "55", "66", "77", "88"], suit: "G" },
        { numbers: ["111", "222", "333", "444", "555", "666", "777"], suit: "R" },
        { numbers: ["222", "333", "444", "555", "666", "777", "888"], suit: "R" },
        { numbers: ["3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "B" },
      ],
      text: "Any 3 Suits, Any 3 Consec. Nos.",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["111", "222", "333", "444", "555", "666"], suit: "B" },
        { numbers: ["222", "333", "444", "555", "666", "777"], suit: "B" },
        { numbers: ["3333", "4444", "5555", "6666", "7777", "8888"], suit: "B" },
        { numbers: ["4444", "5555", "6666", "7777", "8888", "9999"], suit: "B" },
      ],
      text: "Any 1 or 2 Suits, Any 4 Consec. Nos.",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["111", "222", "333", "444", "555", "666"], suit: "G" },
        { numbers: ["222", "333", "444", "555", "666", "777"], suit: "G" },
        { numbers: ["3333", "4444", "5555", "6666", "7777", "8888"], suit: "R" },
        { numbers: ["4444", "5555", "6666", "7777", "8888", "9999"], suit: "R" },
      ],
      text: "Any 1 or 2 Suits, Any 4 Consec. Nos.",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["11", "22", "33", "44", "55", "66", "77"], suit: "B" },
        { numbers: ["22", "33", "44", "55", "66", "77", "88"], suit: "B" },
        { numbers: ["333", "444", "555", "666", "777", "888", "999"], suit: "B" },
        { numbers: ["DDDD"], suit: "B" },
      ],
      text: "Any 1 or 2 Suits, Any Run, Ds Match Middle No.",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["11", "22", "33", "44", "55", "66", "77"], suit: "G" },
        { numbers: ["22", "33", "44", "55", "66", "77", "88"], suit: "R" },
        { numbers: ["333", "444", "555", "666", "777", "888", "999"], suit: "G" },
        { numbers: ["DDDD"], suit: "R" },
      ],
      text: "Any 1 or 2 Suits, Any Run, Ds Match Middle No.",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["1111", "2222", "3333", "4444", "5555", "6666", "7777", "8888"], suit: "B" },
        { numbers: ["FFFFFF"], suit: FLOWER_SUIT },
        { numbers: ["2222", "3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "B" },
      ],
      text: "Any 1 Suit, Any 2 Consec. Nos.",
      value: 30,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["1111", "2222", "3333", "4444", "5555", "6666", "7777"], suit: "B" },
        { numbers: ["2222", "3333", "4444", "5555", "6666", "7777", "8888"], suit: "B" },
        { numbers: ["3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "B" },
      ],
      text: "Any 1 or 3 Suits, Any 3 Consec. Nos.",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["1111", "2222", "3333", "4444", "5555", "6666", "7777"], suit: "G" },
        { numbers: ["2222", "3333", "4444", "5555", "6666", "7777", "8888"], suit: "R" },
        { numbers: ["3333", "4444", "5555", "6666", "7777", "8888", "9999"], suit: "B" },
      ],
      text: "Any 1 or 3 Suits, Any 3 Consec. Nos.",
      value: 25,
      concealed: false,
    },
    {
      section: "Consecutive Run",
      melds: [
        { numbers: ["1", "2", "3", "4", "5", "6"], suit: "G" },
        { numbers: ["22", "33", "44", "55", "66", "77"], suit: "G" },
        { numbers: ["333", "444", "555", "666", "777", "888"], suit: "G" },
        { numbers: ["1", "2", "3", "4", "5", "6"], suit: "R" },
        { numbers: ["22", "33", "44", "55", "66", "77"], suit: "R" },
        { numbers: ["333", "444", "555", "666", "777", "888"], suit: "R" },
        { numbers: ["44", "55", "66", "77", "88", "99"], suit: "B" },
      ],
      text: "Any 3 Suits, Any 4 Consec. Nos.",
      value: 35,
      concealed: true,
    },
    // #endregion

    // #region 13579
    {
      section: "13579",
      melds: [
        { numbers: ["11"], suit: "B" },
        { numbers: ["333"], suit: "B" },
        { numbers: ["55"], suit: "B" },
        { numbers: ["777"], suit: "B" },
        { numbers: ["9999"], suit: "B" },
      ],
      text: "Any 1 or 3 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["11"], suit: "G" },
        { numbers: ["333"], suit: "G" },
        { numbers: ["55"], suit: "R" },
        { numbers: ["777"], suit: "R" },
        { numbers: ["9999"], suit: "B" },
      ],
      text: "Any 1 or 3 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["111"], suit: "G" },
        { numbers: ["333"], suit: "G" },
        { numbers: ["3333"], suit: "R" },
        { numbers: ["5555"], suit: "R" },
      ],
      text: "Any 2 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["555"], suit: "G" },
        { numbers: ["777"], suit: "G" },
        { numbers: ["7777"], suit: "R" },
        { numbers: ["9999"], suit: "R" },
      ],
      text: "Any 2 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["NN"], suit: WIND_SUIT },
        { numbers: ["1111"], suit: "B" },
        { numbers: ["33"], suit: "B" },
        { numbers: ["5555"], suit: "B" },
        { numbers: ["SS"], suit: WIND_SUIT },
      ],
      text: "Any 1 Suit, North and South Only",
      value: 30,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["NN"], suit: WIND_SUIT },
        { numbers: ["5555"], suit: "B" },
        { numbers: ["77"], suit: "B" },
        { numbers: ["9999"], suit: "B" },
        { numbers: ["SS"], suit: WIND_SUIT },
      ],
      text: "Any 1 Suit, North and South Only",
      value: 30,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["113579", "133579", "135579", "135779", "135799"], suit: "G" },
        { numbers: ["1111", "3333", "5555", "7777", "9999"], suit: "R" },
        { numbers: ["1111", "3333", "5555", "7777", "9999"], suit: "B" },
      ],
      text: "Any 3 Suits, Pair Any Odd No., Kongs Match Pair",
      value: 25,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["11"], suit: "B" },
        { numbers: ["33"], suit: "B" },
        { numbers: ["555"], suit: "B" },
        { numbers: ["DDDD"], suit: "B" },
      ],
      text: "Any 1 Suit w Matching Dragon",
      value: 25,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["55"], suit: "B" },
        { numbers: ["77"], suit: "B" },
        { numbers: ["999"], suit: "B" },
        { numbers: ["DDDD"], suit: "B" },
      ],
      text: "Any 1 Suit w Matching Dragon",
      value: 25,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["11"], suit: "G" },
        { numbers: ["33"], suit: "G" },
        { numbers: ["111"], suit: "R" },
        { numbers: ["333"], suit: "R" },
        { numbers: ["5555"], suit: "B" },
      ],
      text: "Any 3 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["55"], suit: "G" },
        { numbers: ["77"], suit: "G" },
        { numbers: ["555"], suit: "R" },
        { numbers: ["777"], suit: "R" },
        { numbers: ["9999"], suit: "B" },
      ],
      text: "Any 3 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["1111"], suit: "B" },
        { numbers: ["33"], suit: "B" },
        { numbers: ["55"], suit: "B" },
        { numbers: ["77"], suit: "B" },
        { numbers: ["9999"], suit: "B" },
      ],
      text: "Any 1 or 2 Suits",
      value: 30,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["1111"], suit: "G" },
        { numbers: ["33"], suit: "R" },
        { numbers: ["55"], suit: "R" },
        { numbers: ["77"], suit: "R" },
        { numbers: ["9999"], suit: "G" },
      ],
      text: "Any 1 or 2 Suits",
      value: 30,
      concealed: false,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["11"], suit: "G" },
        { numbers: ["33"], suit: "G" },
        { numbers: ["55"], suit: "G" },
        { numbers: ["111"], suit: "R" },
        { numbers: ["111"], suit: "B" },
      ],
      text: "Any 3 Suits, These Nos. Only",
      value: 35,
      concealed: true,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["55"], suit: "G" },
        { numbers: ["77"], suit: "G" },
        { numbers: ["99"], suit: "G" },
        { numbers: ["555"], suit: "R" },
        { numbers: ["555"], suit: "B" },
      ],
      text: "Any 3 Suits, These Nos. Only",
      value: 35,
      concealed: true,
    },
    {
      section: "13579",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["135"], suit: "G" },
        { numbers: ["777"], suit: "G" },
        { numbers: ["999"], suit: "G" },
        { numbers: ["DDD"], suit: "R" },
      ],
      text: "Any 1 Suit w Opp. Dragon",
      value: 30,
      concealed: true,
    },
    // #endregion

    // #region WINDS - DRAGONS
    {
      section: "Winds - Dragons",
      melds: [
        { numbers: ["NNNN"], suit: WIND_SUIT },
        { numbers: ["EEE"], suit: WIND_SUIT },
        { numbers: ["WWW"], suit: WIND_SUIT },
        { numbers: ["SSSS"], suit: WIND_SUIT },
      ],
      text: "",
      value: 25,
      concealed: false,
    },
    {
      section: "Winds - Dragons",
      melds: [
        { numbers: ["NNN"], suit: WIND_SUIT },
        { numbers: ["EEEE"], suit: WIND_SUIT },
        { numbers: ["WWWW"], suit: WIND_SUIT },
        { numbers: ["SSS"], suit: WIND_SUIT },
      ],
      text: "",
      value: 25,
      concealed: false,
    },
    {
      section: "Winds - Dragons",
      melds: [
        { numbers: ["1234", "2345", "3456", "4567", "5678", "6789"], suit: "B" },
        { numbers: ["DDD"], suit: "G" },
        { numbers: ["DDD"], suit: "R" },
        { numbers: ["DDDD"], suit: "B" },
      ],
      text: "Any 4 Consec. Nos. in Any 1 Suit, Any 3 Dragons",
      value: 25,
      concealed: false,
    },
    {
      section: "Winds - Dragons",
      melds: [
        { numbers: ["NNN"], suit: WIND_SUIT },
        { numbers: ["1111", "3333", "5555", "7777", "9999"], suit: "G" },
        { numbers: ["1111", "3333", "5555", "7777", "9999"], suit: "R" },
        { numbers: ["SSS"], suit: WIND_SUIT },
      ],
      text: "Any Like Odd Nos. in Any 2 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "Winds - Dragons",
      melds: [
        { numbers: ["EEE"], suit: WIND_SUIT },
        { numbers: ["2222", "4444", "6666", "8888"], suit: "G" },
        { numbers: ["2222", "4444", "6666", "8888"], suit: "R" },
        { numbers: ["WWW"], suit: WIND_SUIT },
      ],
      text: "Any Like Even Nos. in Any 2 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "Winds - Dragons",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["NNNN", "EEEE", "WWWW", "SSSS"], suit: WIND_SUIT },
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["DDDD"], suit: "R" },
      ],
      text: "Any Wind, Any Dragon",
      value: 25,
      concealed: false,
    },
    {
      section: "Winds - Dragons",
      melds: [
        { numbers: ["1"], suit: "G" },
        { numbers: ["N"], suit: WIND_SUIT },
        { numbers: ["2"], suit: "G" },
        { numbers: ["EE"], suit: WIND_SUIT },
        { numbers: ["3"], suit: "G" },
        { numbers: ["WWW"], suit: WIND_SUIT },
        { numbers: ["4"], suit: "G" },
        { numbers: ["SSSS"], suit: WIND_SUIT },
      ],
      text: "Any 1 Suit, These Nos. Only",
      value: 25,
      concealed: false,
    },
    {
      section: "Winds - Dragons",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["NNNN"], suit: WIND_SUIT },
        { numbers: ["SSSS"], suit: WIND_SUIT },
        { numbers: ["DD"], suit: "G" },
        { numbers: ["DD"], suit: "R" },
      ],
      text: "Any 2 Dragons",
      value: 25,
      concealed: false,
    },
    {
      section: "Winds - Dragons",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["EEEE"], suit: WIND_SUIT },
        { numbers: ["WWWW"], suit: WIND_SUIT },
        { numbers: ["DD"], suit: "G" },
        { numbers: ["DD"], suit: "R" },
      ],
      text: "Any 2 Dragons",
      value: 25,
      concealed: false,
    },
    {
      section: "Winds - Dragons",
      melds: [
        { numbers: ["NN"], suit: WIND_SUIT },
        { numbers: ["EEE"], suit: WIND_SUIT },
        { numbers: ["2026"], suit: "G" },
        { numbers: ["WWW"], suit: WIND_SUIT },
        { numbers: ["SS"], suit: WIND_SUIT },
      ],
      text: "2026 Any 1 Suit",
      value: 30,
      concealed: true,
    },
    // #endregion

    // #region 369
    {
      section: "369",
      melds: [
        { numbers: ["333"], suit: "G" },
        { numbers: ["666"], suit: "G" },
        { numbers: ["6666"], suit: "R" },
        { numbers: ["9999"], suit: "R" },
      ],
      text: "Any 2 or 3 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "369",
      melds: [
        { numbers: ["333"], suit: "G" },
        { numbers: ["666"], suit: "B" },
        { numbers: ["6666"], suit: "R" },
        { numbers: ["9999"], suit: "B" },
      ],
      text: "Any 2 or 3 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "369",
      melds: [
        { numbers: ["33"], suit: "G" },
        { numbers: ["66"], suit: "G" },
        { numbers: ["333"], suit: "R" },
        { numbers: ["666"], suit: "R" },
        { numbers: ["9999"], suit: "B" },
      ],
      text: "Any 3 Suits",
      value: 25,
      concealed: false,
    },
    {
      section: "369",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["33"], suit: "B" },
        { numbers: ["666"], suit: "B" },
        { numbers: ["99"], suit: "B" },
        { numbers: ["DDDD"], suit: "B" },
      ],
      text: "1 Suit w Matching or Opp. Dragon",
      value: 25,
      concealed: false,
    },
    {
      section: "369",
      melds: [
        { numbers: ["FFF"], suit: FLOWER_SUIT },
        { numbers: ["33"], suit: "G" },
        { numbers: ["666"], suit: "G" },
        { numbers: ["99"], suit: "G" },
        { numbers: ["DDDD"], suit: "R" },
      ],
      text: "1 Suit w Matching or Opp. Dragon",
      value: 25,
      concealed: false,
    },
    {
      section: "369",
      melds: [
        { numbers: ["33"], suit: "G" },
        { numbers: ["66"], suit: "G" },
        { numbers: ["666"], suit: "R" },
        { numbers: ["999"], suit: "R" },
        { numbers: ["NEWS"], suit: WIND_SUIT },
      ],
      text: "Any 2 Suits",
      value: 30,
      concealed: false,
    },
    {
      section: "369",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["3369", "3669", "3699"], suit: "G" },
        { numbers: ["3333", "6666", "9999"], suit: "R" },
        { numbers: ["3333", "6666", "9999"], suit: "B" },
      ],
      text: "Any 3 Suits, Pair 3,6, or 9, Kongs Match Pair",
      value: 25,
      concealed: false,
    },
    {
      section: "369",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["333"], suit: "G" },
        { numbers: ["666"], suit: "G" },
        { numbers: ["999"], suit: "G" },
        { numbers: ["369"], suit: "R" },
      ],
      text: "Any 2 Suits",
      value: 30,
      concealed: true,
    },
    // #endregion

    // #region SINGLES AND PAIRS
    {
      section: "Singles and Pairs",
      melds: [
        { numbers: ["NN"], suit: WIND_SUIT },
        { numbers: ["EE"], suit: WIND_SUIT },
        { numbers: ["WW"], suit: WIND_SUIT },
        { numbers: ["SS"], suit: WIND_SUIT },
        { numbers: ["1", "2", "3", "4", "5", "6", "7", "8", "9"], suit: "G" },
        { numbers: ["D"], suit: "G" },
        { numbers: ["1", "2", "3", "4", "5", "6", "7", "8", "9"], suit: "R" },
        { numbers: ["D"], suit: "R" },
        { numbers: ["1", "2", "3", "4", "5", "6", "7", "8", "9"], suit: "B" },
        { numbers: ["D"], suit: "B" },
      ],
      text: "Any 3 Suits, Any Like No. w Matching Dragon",
      value: 50,
      concealed: true,
    },
    {
      section: "Singles and Pairs",
      melds: [
        { numbers: ["2"], suit: "G" },
        { numbers: ["4"], suit: "G" },
        { numbers: ["66"], suit: "G" },
        { numbers: ["88"], suit: "G" },
        { numbers: ["2"], suit: "R" },
        { numbers: ["4"], suit: "R" },
        { numbers: ["66"], suit: "R" },
        { numbers: ["88"], suit: "R" },
        { numbers: ["88"], suit: "B" },
      ],
      text: "Any 3 Suits, These Nos. Only",
      value: 50,
      concealed: true,
    },
    {
      section: "Singles and Pairs",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["3369"], suit: "G" },
        { numbers: ["3669"], suit: "R" },
        { numbers: ["3699"], suit: "B" },
      ],
      text: "Any 3 Suits",
      value: 50,
      concealed: true,
    },
    {
      section: "Singles and Pairs",
      melds: [
        { numbers: ["11"], suit: "B" },
        { numbers: ["22"], suit: "B" },
        { numbers: ["33"], suit: "B" },
        { numbers: ["44"], suit: "B" },
        { numbers: ["55"], suit: "B" },
        { numbers: ["66"], suit: "B" },
        { numbers: ["77"], suit: "B" },
      ],
      text: "Any 1 Suit, Any 7 Consec. Nos.",
      value: 50,
      concealed: true,
    },
    {
      section: "Singles and Pairs",
      melds: [
        { numbers: ["11"], suit: "G" },
        { numbers: ["3"], suit: "G" },
        { numbers: ["5"], suit: "G" },
        { numbers: ["7"], suit: "G" },
        { numbers: ["99"], suit: "G" },
        { numbers: ["11"], suit: "R" },
        { numbers: ["3"], suit: "R" },
        { numbers: ["5"], suit: "R" },
        { numbers: ["7"], suit: "R" },
        { numbers: ["99"], suit: "R" },
      ],
      text: "Any 2 Suits",
      value: 50,
      concealed: true,
    },
    {
      section: "Singles and Pairs",
      melds: [
        { numbers: ["FF"], suit: FLOWER_SUIT },
        { numbers: ["2026"], suit: "G" },
        { numbers: ["2026"], suit: "R" },
        { numbers: ["2026"], suit: "B" },
      ],
      text: "Any 3 Suits",
      value: 75,
      concealed: true,
    },
    // #endregion
  ],
};
