import { JOKER_SUIT } from "../../constants";
import { generateCombosForPlayerJokers } from "./generateCombosForPlayerJokers";
import type { NeededData } from "./getDrawingChance";

/**
 * Take a starting set of needed tiles and distribute the drawable jokers amongst them
 * in all possible combinations (0, 1, or 2 jokers, etc) and return the neededTiles for each combination
 * (including the needed jokers)
 */
export const generateCombosForDrawingJokers = (neededTiles: NeededData[], unseenJokerCount: number): NeededData[][] => {
  const allCombos: NeededData[][] = [];
  const totalCallableTiles = neededTiles.reduce((total, need) => total + need.callable, 0);
  const maxAssignableJokers = Math.min(unseenJokerCount, totalCallableTiles);
  for (let i = 0; i <= maxAssignableJokers; i++) {
    // Add all the combos generated by player jokers, and add to each the jokers that would need to be drawn
    let assignmentCombos = generateCombosForPlayerJokers(neededTiles, i)
    if(i > 0) {
      assignmentCombos.forEach((combo) => combo.push({
        tileKey: JOKER_SUIT + "_",
        totalNeeded: i,
        nonCallable: i,
        callable: 0,
      }))
    }
    allCombos.push(...assignmentCombos);
  }
  return allCombos;
};
